### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by chrisverrett** [IBM-Bluemix-Docs/email-delivery#10]
hi, 
i have a customer using this product and going through a sev1 outage.   just trying to find a contact or more information (someone to bug since it's a 3rd party) leads me to this docs page.  https://cloud.ibm.com/docs/email-delivery?topic=email-delivery-getting-started

The link "about this product" is broken.  

looks like sendgrid was recently acquired by Twilio.  perhaps a review of all of our documentation and associated content is in order to make sure customer's can reach the most accurate and up-to-date information.   (including someone to bug for outages :) 

thanks, 
chris

**Comment by jmilst** [comment]
Hi @chrisverrett - These links work for me :) 

https://cloud.ibm.com/docs/email-delivery?topic=email-delivery-getting-started-email-delivery
https://cloud.ibm.com/docs/email-delivery?topic=email-delivery-about-email-delivery

**Comment by chrisverrett** [comment]
That’s great those links work for you.

The original link is still broken, please put a redirect or add content.


Chris Verrett
Sr. Customer Success Manager
IBM Public Cloud, Americas
***@***.******@***.***>
972-877-1281

From: jmilst ***@***.***>
Date: Tuesday, April 25, 2023 at 4:47 PM
To: ibm-cloud-docs/email-delivery ***@***.***>
Cc: Chris Verrett ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [ibm-cloud-docs/email-delivery] broken link (Issue #10)
Hi @chrisverrett - These links work for me :) https: //cloud. ibm. com/docs/email-delivery?topic=email-delivery-getting-started-email-delivery https: //cloud. ibm. com/docs/email-delivery?topic=email-delivery-about-email-delivery —Reply to
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Hi @chrisverrett<https://github.com/chrisverrett> - These links work for me :)

https://cloud.ibm.com/docs/email-delivery?topic=email-delivery-getting-started-email-delivery
https://cloud.ibm.com/docs/email-delivery?topic=email-delivery-about-email-delivery

**Comment by jmilst** [comment]
Ok @chrisverrett - can you tell me where the broken link originates? If it's within the documentation, please share the page. If it's outside of the documentation, it should be directing to https://cloud.ibm.com/docs/email-delivery?topic=email-delivery-getting-started-email-delivery.

**Comment by chrisverrett** [comment]
Appreciate you asking.  No , I cannot tell you where this link originates.

I take it we can agree the link is active and that it leads to a dead page.

For this reason alone it should be redirected

Chris Verrett
Sr. Customer Success Manager
IBM Public Cloud, Americas
***@***.******@***.***>
972-877-1281

From: jmilst ***@***.***>
Date: Wednesday, April 26, 2023 at 10:14 AM
To: ibm-cloud-docs/email-delivery ***@***.***>
Cc: Chris Verrett ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [ibm-cloud-docs/email-delivery] broken link (Issue #10)
Ok @chrisverrett - can you tell me where the broken link originates? If it's within the documentation, please share the page. If it's outside of the documentation, it should be directing to https: //cloud. ibm. com/docs/email-delivery?topic=email-delivery-getting-started-email-delivery. 
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Ok @chrisverrett<https://github.com/chrisverrett> - can you tell me where the broken link originates? If it's within the documentation, please share the page. If it's outside of the documentation, it should be directing to https://cloud.ibm.com/docs/email-delivery?topic=email-delivery-getting-started-email-delivery.

**Comment by jmilst** [comment]
@chrisverrett Going off what you sent:

> i have a customer using this product and going through a sev1 outage. just trying to find a contact or more information (someone to bug since it’s a 3rd party) **leads me to this docs page.** https://cloud.ibm.com/docs/email-delivery?topic=email-delivery-getting-started

The original link that you shared returns `Content not available` because the URL is incorrect. That's why I asked about the origin of the link. If the URL for the link changed, which I suspect that it was many years ago (when had an overhaul of the documentation repos), then the redirect time frame expired years ago. We can't perpetually redirect a link. 

To resolve the issue, the source content that links to the incorrect URL needs to be updated to the correct URL. Apart from that, all that I can do is advise you to click **"Getting started"** in the table of contents on the left to get to the expected page.

**(incorrect)** ~https://cloud.ibm.com/docs/email-delivery?topic=email-delivery-getting-started~ 

**(correct)** https://cloud.ibm.com/docs/email-delivery?topic=email-delivery-getting-started-email-delivery

**Comment by chrisverrett** [comment]
Makes sense.  Most likely I browsed to the page through the docs at the time of incident and it’s possible it’s been fixed since then.  I’d normally open an issue against the page and in this case opened an aha idea which was flipped into this issue at some point.

Appreciate you checking into this and resolving.





Chris Verrett
Sr. Customer Success Manager
IBM Public Cloud, Americas
***@***.******@***.***>
972-877-1281

From: jmilst ***@***.***>
Date: Thursday, April 27, 2023 at 12:28 PM
To: ibm-cloud-docs/email-delivery ***@***.***>
Cc: Chris Verrett ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [ibm-cloud-docs/email-delivery] broken link (Issue #10)
@chrisverrett Going off what you sent: i have a customer using this product and going through a sev1 outage. just trying to find a contact or more information (someone to bug since it’s a 3rd party) leads me to this docs page. https: //cloud. ibm. com/docs/email-delivery?topic=email-delivery-getting-started
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

@chrisverrett<https://github.com/chrisverrett> Going off what you sent:

i have a customer using this product and going through a sev1 outage. just trying to find a contact or more information (someone to bug since it’s a 3rd party) leads me to this docs page. https://cloud.ibm.com/docs/email-delivery?topic=email-delivery-getting-started

The original link that you shared returns Content not available because the URL is incorrect. That's why I asked about the origin of the link. If the URL for the link changed, which I suspect that it was many years ago (when had an overhaul of the documentation repos), then the redirect time frame expired years ago. We can't perpetually redirect a link.

To resolve the issue, the source content that links to the incorrect URL needs to be updated to the correct URL. Apart from that, all that I can do is advise you to click "Getting started" in the table of contents on the left to get to expected page.

(incorrect) https://cloud.ibm.com/docs/email-delivery?topic=email-delivery-getting-started

(correct) https://cloud.ibm.com/docs/email-delivery?topic=email-delivery-getting-started-email-delivery

**Comment by jmilst** [comment]
You're welcome, @chrisverrett 🙌
