### ISSUE TITLE
FAQ for sendgrid billing

### ISSUE THREAD

**Issue by chrisverrett** [IBM-Bluemix-Docs/email-delivery#11]
as noted in customer case CS2829396, it's difficult for customers to easily find their sendgrid charges in their IBM Cloud bill.   Would it be possible add two FAQs for billing?  

1 - how do i find my sengrid charges on my IBM Cloud bill? 

2 - when should i expect sendgrid overages to appear on my bill and how do i find them? 

here is the answer provided in the ticket:
Thank you for following up with me regarding this. Your enterprise package for Sendgrid overages, if you incur any, would be in the detailed billing tab of the excel format bill. I checked the March bill for reference and I didn't see any overages charged on it for you. If you use the find option in the detailed billing tab of he excel format bill and search using the email address you gave me or for Enterprise Package it will locate the Sendgrid package first then if any overages are present it would locate them next. Please let me know if I can assist you with any additional questions. 

similarly, here is an aha for this ask - https://bigblue.aha.io/ideas/ideas/CPS-I-1709

**Comment by chrisverrett** [comment]
request to update FAQ in docs
https://github.com/ibm-cloud-docs/email-delivery/issues/11

**Comment by jmilst** [comment]
Hi @chrisverrett - We don't document billing and pricing in IaaS product documentation. Thanks!

**Comment by chrisverrett** [comment]
Hello, the customer questions still apply.

  *   How does a customer find sendgrid billing on their IBM Cloud bill
  *   When should a customer expect to see sendgrid overages on their bill and how do they find them?

Is a new idea needed to request billing and pricing be documented?



Chris Verrett
Sr. Customer Success Manager
IBM Public Cloud, Americas
***@***.******@***.***>
972-877-1281

From: jmilst ***@***.***>
Date: Tuesday, April 25, 2023 at 4:48 PM
To: ibm-cloud-docs/email-delivery ***@***.***>
Cc: Chris Verrett ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [ibm-cloud-docs/email-delivery] FAQ for sendgrid billing (Issue #11)
Hi @chrisverrett - We don't document billing and pricing in IaaS product documentation. Thanks! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <ibm-cloud-docs/email-delivery/issues/11/1522463324@ github. com>
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Hi @chrisverrett<https://github.com/chrisverrett> - We don't document billing and pricing in IaaS product documentation. Thanks!

**Comment by jmilst** [comment]
Not sure what you mean by "_Is a new idea needed to request billing and pricing be documented?_" The only suggestion that I have for pricing and billing is to get with OM or sales and marketing.
