### ISSUE TITLE
Pricing and Packages 

### ISSUE THREAD

**Issue by henenel5** [IBM-Bluemix-Docs/email-delivery#4]
Currently the Email Delivery documentation doesn't provide public facing pricing of each plan that we offer and description of  each package and the benefits. We are currently sharing this 3rd party link with client to view the Pricing and Plan details https://sendgrid.com/pricing/

**Comment by jmilst** [comment]
Hi @henenel5. This is end user technical documentation. For pricing information, you need to contact your sales representative or offering manager.
