### ISSUE TITLE
How do you upgrade your plan?

### ISSUE THREAD

**Issue by bwentwor** [IBM-Bluemix-Docs/email-delivery#5]
The information here is missing one glaring piece of information: How do you upgrade your plan? I have had a customer ask this question and it's not covered in the documentation. It is also not available when I do a Google search. There is information about how to upgrade outside of IBM Cloud, but not when you sign up for the service through IBM Cloud.

**Comment by RZurchin** [comment]
I will try to help.  There are a few pieces of information needed:
Who is the client?
What platform are they on?
What plan are they on?
Why do they need to change? (Have they reached the plan limit?)
What plan do they want to move up to?

**Comment by stemke** [comment]
@bwentwor @RZurchin - Thank you for feedback and questions.  Since this is a public forum, I'm requesting that @jmilst follow up with you both offline, so we can address any future requirements or enhancements.  Thanks again.
