### ISSUE TITLE
Instructions are inappropriate

### ISSUE THREAD

**Issue by thowden** [IBM-Bluemix-Docs/email-delivery#8]
The first instruction on this page is impossible to complete:
**Confirm that you can send emails from the device before you add or update smart host settings. Fix any existing problems in the send and receive process before you proceed.**

All outbound mail on port 25 is blocked by IBM. So if outbound mail is blocked, how can it be tested, until after the smarthost is configured ?

**Comment by jmilst** [comment]
Hi @thowden. Can you please share what documentation page you are referring to? Thanks!
