### ISSUE TITLE
Is this service deprecated or has it been replaced?

### ISSUE THREAD

**Issue by danieloflanagan** [IBM-Bluemix-Docs/email-delivery#9]
Hi, is this service deprecated?

**Comment by jmilst** [comment]
Hi @danieloflanagan. These issues are used for documentation feedback. If you have questions about the product, you can [contact support](https://cloud.ibm.com/docs/get-support?topic=get-support-using-avatar) or reach out to your IBM product representative or product manager. Thanks!
